ast_items = [
    ["ast", "struct", "SourceFile", ["stmts", ["Vec", "Stmt"]]],
    [
        "ast",
        "enum",
        "Stmt",
        ["Expr", ["Box", "Expr"]],
        ["Block", "Block"],
        ["Return", ["Option", "Expr"]],
        ["VarDecl", "DeclType", "Pattern", ["Option", "Expr"]],
        ["If", ["Box", "Expr"], ["Box", "Stmt"], ["Option", ["Box", "Stmt"]]],
        ["While", ["Box", "Expr"], ["Box", "Stmt"]],
        ["Try", ["Box", "TryStmt"]],
    ],
    [
        "ast",
        "struct",
        "TryStmt",
        ["try_block", "Block"],
        ["catch_name", ["Option", "Ident"]],
        ["catch_block", ["Option", "Block"]],
        ["finally_block", ["Option", "Block"]],

    ],
    [
        "ast",
        "enum",
        "Expr",
        ["Var", "Ident"],
        ["BinOp", ["Box", "Expr"], "BinOp", ["Box", "Expr"]],
        ["ArrowFn", "ParamList", "ArrowFnBody"],
        ["Function", ["Option", "Ident"], "ParamList", "Block"],
        ["Call", ["Box", "Expr"], ["Vec", "Expr"]],
        ["Index", ["Box", "Expr"], ["Box", "Expr"]],
        ["Prop", ["Box", "Expr"], "Ident"],
        ["String", "Text"],
        ["Number", "Text"],
        ["Object", ["Vec", "ObjectLiteralEntry"]],
        ["Throw", ["Box", "Expr"]],
    ],
    ["ast", "struct", "ObjectLiteralEntry", ["key", "Ident"], ["value", "Expr"]],
    ["ast", "enum", "Pattern", ["Var", "Ident"]],
    [
        "ast",
        "struct",
        "ParamList",
        ["params", ["Vec", "Param"]],
    ],
    [
        "ast",
        "enum",
        "ArrowFnBody",
        ["Expr", ["Box", "Expr"]],
        ["Block", "Block"],
    ],
    [
        "ast",
        "struct",
        "Block",
        ["stmts", ["Vec", "Stmt"]],
    ],
    [
        "ast",
        "struct",
        "Param",
        ["name", "Ident"],
    ],
    [
        "enum",
        "BinOp",
        "Add",
        "Sub",
        "Mul",
        "Div",
    ],
    [
        "enum",
        "DeclType",
        "Let",
        "Const",
        "Var",
    ],
]
