from typing import ForwardRef, Optional, Union
import types
from src.djs.include.djs.syntax.ast import Expression, Statement, VariantRoot, Box, Pattern, StructRoot, FormalParams, Block
import argparse

def main() -> None:
  args = parse_args()
  code = """
#pragma once
/// Generated by python3 gen_ast.py --interface_output src/djs/include/djs/syntax/ast.gen.hpp --implementation_output src/djs/syntax/ast.gen.cc
/// DO NOT EDIT BY HAND

#include <string>
#include <utility>
#include "dlib/Box.hpp"
#include "dlib/Opt.hpp"
#include "./NodeList.hpp"
#include "./ParseNode.hpp"
#include "./SourceLocation.hpp"
namespace djs {
struct Expression;
struct Statement;
struct Block;
struct Pattern;
struct FormalParams;

"""
  code += gen(Pattern, interface=True)
  code += gen_struct_root(FormalParams, interface=True)
  code += gen(Expression, interface=True)
  code += gen(Statement, interface=True)
  code += gen_struct_root(Block, interface=True)

  code += "} // namespace djs"

  with open(args.interface_output, 'w') as f:
    f.write(code)

  code = f"""
/// Generated by python3 gen_ast.py --interface_output src/djs/include/djs/syntax/ast.gen.hpp --implementation_output src/djs/syntax/ast.gen.cc
/// DO NOT EDIT BY HAND
#include "dlib/Box.hpp"
#include "dlib/Opt.hpp"
#include "djs/syntax/SourceLocation.hpp"
#include "djs/syntax/NodeList.hpp"
#include "djs/syntax/ParseNode.hpp"
#include "djs/syntax/ast.gen.hpp"
namespace djs {{
"""
  code += gen(Pattern, interface=False)
  code += gen_struct_root(FormalParams, interface=False)
  code += gen(Expression, interface=False)
  code += gen(Statement, interface=False)
  code += gen_struct_root(Block, interface=False)
  code += "} // namespace djs"

  with open(args.implementation_output, 'w') as f:
    f.write(code)

def parse_args():
  p = argparse.ArgumentParser()
  p.add_argument('--interface_output', required=True)
  p.add_argument('--implementation_output', required=True)

  return p.parse_args()

def gen_field(name: str, ty: type) -> str:
  return f'{annotation_to_cpptype(ty)} {name};'

def gen_ostream_operator_signature(cl: type[StructRoot]) -> str:
  return f"std::ostream &operator<<(std::ostream &os, const {cl.__name__} &self)"

def gen_ostream_operator(cl: type[StructRoot]) -> str:
  statements = '\n'.join([
    f'  os << self.{name} << "\\n";' for name in cl.fields().keys()
  ])
  return f"""
{gen_ostream_operator_signature(cl)} {{
{statements}
  return os;
}}
""".strip()

def gen_struct_root(cl: type[StructRoot], interface:bool) -> str:
  constructor_params = ', '.join(
    ['SourceLocation location'] +
    [f'{annotation_to_cpptype(typ)} {name}' for (name, typ) in cl.fields().items()])
  if interface:
    ostream_operator = f"{gen_ostream_operator_signature(cl)};"
    constructor = f'{cl.__name__}({constructor_params});'
    fields = '\n'.join(['  ' + gen_field(name, typ) for (name, typ) in cl.fields().items()])
    return f"""
struct {cl.__name__}: public ParseNode {{
{fields}

  {constructor}
}};

{ostream_operator}
  """.strip()
  else:
    constructor_init = ', '.join(
      ['ParseNode(location)'] +
      [
        f'{name}({name})' for name, _ in cl.fields().items()
      ])
    return f"""
{cl.__name__}::{cl.__name__}({constructor_params}): {constructor_init} {{}}
{gen_ostream_operator(cl)}
"""
def gen(base: type[VariantRoot], interface: bool) -> str:
  base_name = base.__name__
  ostream_operator_sig = f"std::ostream& operator<<(std::ostream& os, const {base_name}& e)"

  if interface:
    expr_structs = '\n'.join([gen_variant_struct(base_name, c, interface=True) for c in base.classes()])
    kind_names = ',\n    '.join([ c.__name__ for c in  base.classes() ])
    return f"""
struct {base_name}: public ParseNode {{
  enum class Kind {{
    {kind_names}
  }};
  Kind kind;

  {base_name}(SourceLocation location, Kind kind): ParseNode(location), kind(kind) {{}}

  template <typename T>
    requires std::is_assignable_v<{base_name}, T>
  auto as() const -> const T& {{
    const auto& self = this;
    return dynamic_cast<const T&>(*self);
  }}
}};
{ostream_operator_sig};
{expr_structs}
"""
  else:
    ostream_cases = '\n'.join([
      f'    case {base_name}::Kind::{c.__name__}:\n' + \
        f'      os << e.as<{c.__name__}{base_name}>();\n' + \
        '      return os;'
      for c in base.classes()
    ])
    constructors = '\n\n'.join([gen_variant_struct(base.__name__, c, interface=False) for c in base.classes()])
    return f"""
{constructors}
{ostream_operator_sig} {{
  switch(e.kind) {{
  {ostream_cases}
  }}
  return os;
}}
"""

def is_boxed(annotation) -> bool:
  return hasattr(annotation, '__origin__') and annotation.__origin__ == Box

def annotation_to_cpptype(annotation, unwrap_unique_ptr: bool=False) -> str:
  def go(annotation):
    if isinstance(annotation, str):
      return annotation;
    elif annotation == str:
      return 'std::string'
    elif isinstance(annotation, ForwardRef):
      return go(annotation._evaluate(globals(), locals(), frozenset()))
    elif isinstance(annotation, type):
      return annotation.__name__
    elif inner:= as_nullable(annotation):
      return f'Opt<{go(inner)}>'
    elif hasattr(annotation, '__origin__'):
      if annotation.__origin__ == Box:
        if unwrap_unique_ptr:
          return go(annotation.__args__[0])
        else:
          return f'Box<{go(annotation.__args__[0])}>'
      elif annotation.__origin__ == list:
        return f'NodeList<{go(annotation.__args__[0])}>'
      else:
        raise TypeError(annotation)
    else:
      raise TypeError(annotation)
  return go(annotation)

def as_nullable(annotation: type) -> type | None:
  if isinstance(annotation, types.UnionType) \
    and len(annotation.__args__) == 2 \
    and (
      annotation.__args__[0] == None.__class__ \
      or annotation.__args__[1] == None.__class__
    ):
    return annotation.__args__[0] if annotation.__args__[1] == None.__class__ else annotation.__args__[1]
  elif hasattr(annotation, '__origin__') and annotation.__origin__ == Union \
    and len(annotation.__args__) == 2 \
    and (
      annotation.__args__[0] == None.__class__ \
      or annotation.__args__[1] == None.__class__
    ):
    return annotation.__args__[0] if annotation.__args__[1] == None.__class__ else annotation.__args__[1]
  else:
    return None

def gen_variant_struct(base_name: str, cls: type, interface: bool) -> str:
  params = ', '.join(['SourceLocation location'] + [
      f'{annotation_to_cpptype(annotation)} {arg_n}'
      for (arg_n, annotation) in cls.__annotations__.items()
  ])
  stream_output_operator_signature = f"std::ostream& operator<<(std::ostream& os, const {cls.__name__}{base_name}& self)"
  if interface:
    args_fields = ';\n  '.join([
        f'{annotation_to_cpptype(annotation)} {name}' for name, annotation in cls.__annotations__.items()
    ])
    all_args_constructor = f"""
{cls.__name__}{base_name}({params});
""".strip()
    return f"""struct {cls.__name__}{base_name} : public {base_name} {{
  {args_fields};

  {all_args_constructor}
}};

{stream_output_operator_signature};
"""
  else:
    field_initializers = ', '.join([f'{base_name}(location, Kind::{cls.__name__})'] + [
      f'{arg_n}(std::move({arg_n}))'
      for (arg_n, _) in cls.__annotations__.items()
    ])
    stream_out_members = "\n  ".join([
      f"""os << self.{name} << ',';"""
          for name in
          cls.__annotations__.keys()
        ])
    stream_output_operator = f"""
  {stream_output_operator_signature} {{
  os << "{cls.__name__}" << "(";
  {stream_out_members}
  os << ")" << std::endl;
  return os;
}}
""".strip()
    return f"""
{cls.__name__}{base_name}::{cls.__name__}{base_name}({params}): {field_initializers} {{}}

{stream_output_operator}
""".strip()


if __name__ == '__main__':
    main()
