
/// Generated by python3 gen_ast.py --interface_output src/djs/include/djs/syntax/ast.gen.hpp --implementation_output src/djs/syntax/ast.gen.cc
/// DO NOT EDIT BY HAND
#include "dlib/Box.hpp"
#include "dlib/Opt.hpp"
#include "djs/syntax/SourceLocation.hpp"
#include "djs/syntax/NodeList.hpp"
#include "djs/syntax/ParseNode.hpp"
#include "djs/syntax/ast.gen.hpp"
namespace djs {

IdentifierPattern::IdentifierPattern(SourceLocation location, std::string name): Pattern(location, Kind::Identifier), name(std::move(name)) {}

std::ostream& operator<<(std::ostream& os, const IdentifierPattern& self) {
  os << "Identifier" << "(";
  os << self.name << ',';
  os << ")" << std::endl;
  return os;
}
std::ostream& operator<<(std::ostream& os, const Pattern& e) {
  switch(e.kind) {
      case Pattern::Kind::Identifier:
      os << e.as<IdentifierPattern>();
      return os;
  }
  return os;
}

FormalParams::FormalParams(SourceLocation location, NodeList<Pattern> params, Opt<Pattern> rest_param): ParseNode(location), params(params), rest_param(rest_param) {}
std::ostream &operator<<(std::ostream &os, const FormalParams &self) {
  os << self.params << "\n";
  os << self.rest_param << "\n";
  return os;
}

CallExpression::CallExpression(SourceLocation location, Box<Expression> callee, NodeList<Expression> arguments): Expression(location, Kind::Call), callee(std::move(callee)), arguments(std::move(arguments)) {}

std::ostream& operator<<(std::ostream& os, const CallExpression& self) {
  os << "Call" << "(";
  os << self.callee << ',';
  os << self.arguments << ',';
  os << ")" << std::endl;
  return os;
}

VarExpression::VarExpression(SourceLocation location, std::string name): Expression(location, Kind::Var), name(std::move(name)) {}

std::ostream& operator<<(std::ostream& os, const VarExpression& self) {
  os << "Var" << "(";
  os << self.name << ',';
  os << ")" << std::endl;
  return os;
}
std::ostream& operator<<(std::ostream& os, const Expression& e) {
  switch(e.kind) {
      case Expression::Kind::Call:
      os << e.as<CallExpression>();
      return os;
    case Expression::Kind::Var:
      os << e.as<VarExpression>();
      return os;
  }
  return os;
}

ReturnStatement::ReturnStatement(SourceLocation location, Opt<Box<Expression>> value): Statement(location, Kind::Return), value(std::move(value)) {}

std::ostream& operator<<(std::ostream& os, const ReturnStatement& self) {
  os << "Return" << "(";
  os << self.value << ',';
  os << ")" << std::endl;
  return os;
}

FunctionStatement::FunctionStatement(SourceLocation location, std::string name, FormalParams params, Box<Block> body): Statement(location, Kind::Function), name(std::move(name)), params(std::move(params)), body(std::move(body)) {}

std::ostream& operator<<(std::ostream& os, const FunctionStatement& self) {
  os << "Function" << "(";
  os << self.name << ',';
  os << self.params << ',';
  os << self.body << ',';
  os << ")" << std::endl;
  return os;
}
std::ostream& operator<<(std::ostream& os, const Statement& e) {
  switch(e.kind) {
      case Statement::Kind::Return:
      os << e.as<ReturnStatement>();
      return os;
    case Statement::Kind::Function:
      os << e.as<FunctionStatement>();
      return os;
  }
  return os;
}

Block::Block(SourceLocation location, NodeList<Statement> statements): ParseNode(location), statements(statements) {}
std::ostream &operator<<(std::ostream &os, const Block &self) {
  os << self.statements << "\n";
  return os;
}
} // namespace djs