
#pragma once
/// Generated by python3 gen_ast.py > src/djs/include/djs/syntax/ast.gen.hpp
/// DO NOT EDIT BY HAND

#include <string>
#include "./ast_common.hpp"
#include "../Common.hpp"
#include "./NodeList.hpp"
#include "./ParseNode.hpp"
namespace djs {
struct Expression: public ParseNode {
  enum Kind {
    Call,
    Var
  };
  Kind kind;

  Expression(SourceLocation location): ParseNode(location) {}

  template <typename T>
    requires std::is_assignable_v<Expression, T>
  auto as() const -> const T& {
    const auto& self = this;
    return dynamic_cast<const T&>(*self);
  }
};
struct CallExpression : public Expression {
  std::unique_ptr<Expression> callee;
  NodeList<Expression> arguments;

  CallExpression(SourceLocation location, std::unique_ptr<Expression> callee, NodeList<Expression> arguments): Expression(location), callee(std::move(callee)), arguments(std::move(arguments)) {}

  friend std::ostream& operator<<(std::ostream& os, const CallExpression& self);
};

std::ostream& operator<<(std::ostream& os, const CallExpression& self) {
  os << "Call" << "(\n";
  os << "  " << self.callee << ',';
  os << "  " << self.arguments << ',';
  os << ")" << std::endl;
  return os;
}

struct VarExpression : public Expression {
  std::string name;

  VarExpression(SourceLocation location, std::string name): Expression(location), name(std::move(name)) {}

  friend std::ostream& operator<<(std::ostream& os, const VarExpression& self);
};

std::ostream& operator<<(std::ostream& os, const VarExpression& self) {
  os << "Var" << "(\n";
  os << "  " << self.name << ',';
  os << ")" << std::endl;
  return os;
}


std::ostream& operator<<(std::ostream& os, const Expression& e) {
  switch (e.kind) {
    case Expression::Kind::Call: os << e.as<CallExpression>(); return os;
    case Expression::Kind::Var: os << e.as<VarExpression>(); return os;
  }
}


struct Statement: public ParseNode {
  enum Kind {
    Return
  };
  Kind kind;

  Statement(SourceLocation location): ParseNode(location) {}

  template <typename T>
    requires std::is_assignable_v<Statement, T>
  auto as() const -> const T& {
    const auto& self = this;
    return dynamic_cast<const T&>(*self);
  }
};
struct ReturnStatement : public Statement {
  Opt<std::unique_ptr<Expression>> value;

  ReturnStatement(SourceLocation location, Opt<std::unique_ptr<Expression>> value): Statement(location), value(std::move(value)) {}

  friend std::ostream& operator<<(std::ostream& os, const ReturnStatement& self);
};

std::ostream& operator<<(std::ostream& os, const ReturnStatement& self) {
  os << "Return" << "(\n";
  os << "  " << self.value << ',';
  os << ")" << std::endl;
  return os;
}


std::ostream& operator<<(std::ostream& os, const Statement& e) {
  switch (e.kind) {
    case Statement::Kind::Return: os << e.as<ReturnStatement>(); return os;
  }
}

} // namespace djs
