
#pragma once
/// Generated by python3 gen_ast.py --interface_output src/djs/include/djs/syntax/ast.gen.hpp --implementation_output src/djs/syntax/ast.gen.cc
/// DO NOT EDIT BY HAND

#include <string>
#include <utility>
#include "dlib/Box.hpp"
#include "dlib/Opt.hpp"
#include "./NodeList.hpp"
#include "./ParseNode.hpp"
#include "./SourceLocation.hpp"
namespace djs {
struct Expression;
struct Statement;
struct Block;
struct Pattern;
struct FormalParams;


struct Pattern: public ParseNode {
  enum class Kind {
    Identifier
  };
  Kind kind;

  Pattern(SourceLocation location, Kind kind): ParseNode(location), kind(kind) {}

  template <typename T>
    requires std::is_assignable_v<Pattern, T>
  auto as() const -> const T& {
    const auto& self = this;
    return dynamic_cast<const T&>(*self);
  }
};
std::ostream& operator<<(std::ostream& os, const Pattern& e);
struct IdentifierPattern : public Pattern {
  std::string name;

  IdentifierPattern(SourceLocation location, std::string name);

  friend std::ostream& operator<<(std::ostream& os, const IdentifierPattern& self);
};

std::ostream& operator<<(std::ostream& os, const IdentifierPattern& self);

struct FormalParams: public ParseNode {
  NodeList<Pattern> params;
  Opt<Pattern> rest_param;

  FormalParams(SourceLocation location, NodeList<Pattern> params, Opt<Pattern> rest_param);
};

std::ostream &operator<<(std::ostream &os, const FormalParams &self);
struct Expression: public ParseNode {
  enum class Kind {
    Call,
    Var
  };
  Kind kind;

  Expression(SourceLocation location, Kind kind): ParseNode(location), kind(kind) {}

  template <typename T>
    requires std::is_assignable_v<Expression, T>
  auto as() const -> const T& {
    const auto& self = this;
    return dynamic_cast<const T&>(*self);
  }
};
std::ostream& operator<<(std::ostream& os, const Expression& e);
struct CallExpression : public Expression {
  Box<Expression> callee;
  NodeList<Expression> arguments;

  CallExpression(SourceLocation location, Box<Expression> callee, NodeList<Expression> arguments);

  friend std::ostream& operator<<(std::ostream& os, const CallExpression& self);
};

std::ostream& operator<<(std::ostream& os, const CallExpression& self);

struct VarExpression : public Expression {
  std::string name;

  VarExpression(SourceLocation location, std::string name);

  friend std::ostream& operator<<(std::ostream& os, const VarExpression& self);
};

std::ostream& operator<<(std::ostream& os, const VarExpression& self);


struct Statement: public ParseNode {
  enum class Kind {
    Return,
    Function
  };
  Kind kind;

  Statement(SourceLocation location, Kind kind): ParseNode(location), kind(kind) {}

  template <typename T>
    requires std::is_assignable_v<Statement, T>
  auto as() const -> const T& {
    const auto& self = this;
    return dynamic_cast<const T&>(*self);
  }
};
std::ostream& operator<<(std::ostream& os, const Statement& e);
struct ReturnStatement : public Statement {
  Opt<Box<Expression>> value;

  ReturnStatement(SourceLocation location, Opt<Box<Expression>> value);

  friend std::ostream& operator<<(std::ostream& os, const ReturnStatement& self);
};

std::ostream& operator<<(std::ostream& os, const ReturnStatement& self);

struct FunctionStatement : public Statement {
  std::string name;
  FormalParams params;
  Box<Block> body;

  FunctionStatement(SourceLocation location, std::string name, FormalParams params, Box<Block> body);

  friend std::ostream& operator<<(std::ostream& os, const FunctionStatement& self);
};

std::ostream& operator<<(std::ostream& os, const FunctionStatement& self);

struct Block: public ParseNode {
  NodeList<Statement> statements;

  Block(SourceLocation location, NodeList<Statement> statements);
};

std::ostream &operator<<(std::ostream &os, const Block &self);} // namespace djs