name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  CI:
    name: Run CI

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 23
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Run tests
      run: pnpm vitest --coverage
      working-directory: djs_frontend

    - name: Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        # Repository upload token - get it from codecov.io. Required only for private repositories
        # token: # optional
        # Specify whether the Codecov output should be verbose
        verbose: true
        fail_ci_if_error: true
        files:
